name: health_tracker_app
description: A simple health tracker with charts, theme and history.

publish_to: 'none'

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  shared_preferences: ^2.2.2
  fl_chart: ^0.68.0

dev_dependencies:
  flutter_test:
    sdk: flutter